const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_ALL_PRICE_SUCCESS: 'FETCH_ALL_PRICE_SUCCESS',
    FETCH_ALL_PRICE_FAIL: 'FETCH_ALL_PRICE_FAIL',

    // order
    INIT_TABLE_ORDER_SUCCESS: 'INIT_TABLE_ORDER_SUCCESS',
    INIT_TABLE_ORDER_FAIL: 'INIT_TABLE_ORDER_FAIL',
});

export default actionTypes;
